### ISSUE TITLE
Problem Suggestion

### ISSUE THREAD

**Issue by JonoCode9374** [JonoCode9374/100-Little-Keg-Exercises#1]
# Challenge Name
_Type a short description here_. Throughout this exercise you will learn about:

- Aspect learnt about
- Another aspect learnt about
- And so on

## The Challenge

I want you to write a program that:

- Describe task in a series of bullet points

You will need to know these things:

- Things that Keggers need to know about aspects needed to solve challenge

## Solution

_Place a link to an external copy of the solution here as to not spoil anything_

**Comment by A-ee** [comment]
So this might be an overly large step...
## Mike's asterisks
In this task, you should simulate Mike asking for asterisks (explained later on). Throughout this exercise you will learn about:
* Accumulators ```&```
* To be changed later on...
## The Challenge
I want you to write a program that:
* Asks for a string
* Output ```Hello, ``` with the inputted string
* Take a decimal number
* Output asterisks ```*``` that many times
* Exit the program.
You will need to know these things:
* I don't know until I write my program.
## Solution
To be edited...
